{
  "openapi": "3.0.0",
  "info": {
    "title": "Ecommerce API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://ecommerce-api-e7iw.onrender.com"
    }
  ],
  "tags": [
    {
      "name": "Auth"
    },
    {
      "name": "Users"
    },
    {
      "name": "Products"
    },
    {
      "name": "Reviews"
    },
    {
      "name": "Orders"
    }
  ],
  "components": {
    "cookieAuth": {
      "type": "apiKey",
      "in": "cookie",
      "name": "jwt"
    }
  },
  "paths": {
    "/auth/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Register user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "test0",
                  "email": "eao71845@kisoq.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Success! Please check your email to verify your account!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Login user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "eao71845@kisoq.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "user": {
                      "userID": "674d9f90a5621de9520ebe2d",
                      "name": "mg111",
                      "role": "user"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "delete": {
        "tags": [
          "Auth"
        ],
        "summary": "Logout user",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "msg": "User logged out!"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "msg": "Unauthorized"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/verify-email?verificationToken={token}&email={email}": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Verify email",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Email verified!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/reset-password": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Reset password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "pin68740@kisoq.com",
                  "password": "1234567",
                  "token": "6f11f173d9b35574592dfbbcebfcb536ab3f7c2b3b45468edb6e2f54e0138c65c0b5ca8b587b9e58e0a758924e2968bc1986ddc28ba8f99fc679fab712c6146e49f9c0825da8"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Password successfully reset!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/forgot-password": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Forgot password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "pin68740@kisoq.com"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Please check your email to reset your password!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get all users",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "users": [
                      {
                        "name": "test2",
                        "email": "test2@gmail.com",
                        "role": "user",
                        "isVerified": true,
                        "verified": "2023-08-19T16:21:56.643Z",
                        "id": "64e0ec0163d91940458da7d1"
                      },
                      {
                        "name": "test",
                        "email": "test@gmail.com",
                        "role": "user",
                        "isVerified": true,
                        "verified": "2023-08-19T16:21:56.643Z",
                        "id": "64e0ec0163d91940458da7d1"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "msg": "Unauthorized"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/64e0ec0163d91940458da7d1": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get single user",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "user": {
                      "name": "test",
                      "email": "test@gmail.com",
                      "role": "user",
                      "isVerified": true,
                      "verified": "2023-08-19T16:21:56.643Z",
                      "id": "64e0ec0163d91940458da7d1"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/showMe": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Show current user",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "type": "object",
                      "properties": {
                        "userID": {
                          "type": "string",
                          "example": "645f977f0b52892c311eb265"
                        },
                        "name": {
                          "type": "string",
                          "example": "test"
                        },
                        "role": {
                          "type": "string",
                          "example": "user"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/updateUser": {
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Update user",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "test2",
                  "email": "test2@gmail.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "user": {
                      "userID": "674d9f90a5621de9520ebe2d",
                      "name": "test2",
                      "role": "user"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/updateUserPassword": {
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Update user password",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "oldPassword": "123456",
                  "newPassword": "1234567"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "msg": "Password updated!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get all products",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "products": [
                      {
                        "name": "accent Chairrr",
                        "price": 25999,
                        "description": "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                        "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                        "category": "office",
                        "company": "marcos",
                        "colors": [
                          "#ff0000",
                          "#00ff00",
                          "#0000ff"
                        ],
                        "featured": false,
                        "freeShipping": false,
                        "inventory": 15,
                        "averageRating": 1,
                        "numOfReviews": 2,
                        "user": "645f977f0b52892c311eb265",
                        "createdAt": "2024-12-01T11:24:58.173Z",
                        "updatedAt": "2024-12-01T20:57:54.683Z",
                        "id": "674c478a397a664d48cd8aec"
                      }
                    ],
                    "count": 1
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Create product",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "accent chair",
                  "price": 25999,
                  "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                  "colors": [
                    "#ff0000",
                    "#00ff00",
                    "#0000ff"
                  ],
                  "company": "marcos",
                  "description": "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                  "category": "office"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "product": {
                      "name": "accent chair",
                      "price": 25999,
                      "description": "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                      "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                      "category": "office",
                      "company": "marcos",
                      "colors": [
                        "#ff0000",
                        "#00ff00",
                        "#0000ff"
                      ],
                      "featured": false,
                      "freeShipping": false,
                      "inventory": 15,
                      "averageRating": 0,
                      "numOfReviews": 0,
                      "user": "645f977f0b52892c311eb265",
                      "createdAt": "2025-03-02T21:41:29.715Z",
                      "updatedAt": "2025-03-02T21:41:29.715Z",
                      "id": "67c4d089ded572688c4eb283"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/674c478a397a664d48cd8aec": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get single product",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "product": {
                      "name": "accent Chairrr",
                      "price": 25999,
                      "description": "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                      "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                      "category": "office",
                      "company": "marcos",
                      "colors": [
                        "#ff0000",
                        "#00ff00",
                        "#0000ff"
                      ],
                      "featured": false,
                      "freeShipping": false,
                      "inventory": 15,
                      "averageRating": 1,
                      "numOfReviews": 2,
                      "user": "645f977f0b52892c311eb265",
                      "createdAt": "2024-12-01T11:24:58.173Z",
                      "updatedAt": "2024-12-01T20:57:54.683Z",
                      "id": "674c478a397a664d48cd8aec"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/674c478a397a664d48cd8aec/": {
      "patch": {
        "tags": [
          "Products"
        ],
        "summary": "Update product",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "accent Chairrr"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "product": {
                      "name": "accent Chairrr",
                      "price": 25999,
                      "description": "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                      "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                      "category": "office",
                      "company": "marcos",
                      "colors": [
                        "#ff0000",
                        "#00ff00",
                        "#0000ff"
                      ],
                      "featured": false,
                      "freeShipping": false,
                      "inventory": 15,
                      "averageRating": 1,
                      "numOfReviews": 2,
                      "user": "645f977f0b52892c311eb265",
                      "createdAt": "2024-12-01T11:24:58.173Z",
                      "updatedAt": "2025-03-02T21:53:58.482Z",
                      "id": "674c478a397a664d48cd8aec"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/64289a8c38b77a3abccf6496": {
      "delete": {
        "tags": [
          "Products"
        ],
        "summary": "Delete product",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "msg": "Product deleted successfully!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/uploadImage": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Upload image",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "image": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "image": "/uploads/couch.jpeg"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/674c478a397a664d48cd8aec/reviews": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get single product reviews",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "reviews": [
                      {
                        "_id": "674c6560da10648cb48050fe",
                        "rating": 1,
                        "title": "Review 2",
                        "comment": "Comment 2",
                        "user": "64e0ec0163d91940458da7d1",
                        "product": "674c478a397a664d48cd8aec",
                        "createdAt": "2024-12-01T13:32:16.484Z",
                        "updatedAt": "2024-12-01T13:32:16.484Z",
                        "id": "674c6560da10648cb48050fe"
                      },
                      {
                        "_id": "674ccdd21058f14d27c5d7a4",
                        "rating": 1,
                        "title": "Review 3",
                        "comment": "Comment 3",
                        "user": "6748434b1a1bf4ac4f5ee0e6",
                        "product": "674c478a397a664d48cd8aec",
                        "createdAt": "2024-12-01T20:57:54.472Z",
                        "updatedAt": "2024-12-01T20:57:54.472Z",
                        "id": "674ccdd21058f14d27c5d7a4"
                      }
                    ],
                    "count": 2
                  }
                }
              }
            }
          }
        }
      }
    },
    "/reviews": {
      "get": {
        "tags": [
          "Reviews"
        ],
        "summary": "Get all reviews",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "reviews": [
                      {
                        "rating": 1,
                        "title": "Review 2",
                        "comment": "Comment 2",
                        "user": {
                          "name": "test2",
                          "id": "64e0ec0163d91940458da7d1"
                        },
                        "product": {
                          "name": "accent Chairrr",
                          "price": 25999,
                          "company": "marcos",
                          "id": "674c478a397a664d48cd8aec"
                        },
                        "createdAt": "2024-12-01T13:32:16.484Z",
                        "updatedAt": "2024-12-01T13:32:16.484Z",
                        "id": "674c6560da10648cb48050fe"
                      },
                      {
                        "rating": 1,
                        "title": "Review 3",
                        "comment": "Comment 3",
                        "user": {
                          "name": "mg11",
                          "id": "6748434b1a1bf4ac4f5ee0e6"
                        },
                        "product": {
                          "name": "accent Chairrr",
                          "price": 25999,
                          "company": "marcos",
                          "id": "674c478a397a664d48cd8aec"
                        },
                        "createdAt": "2024-12-01T20:57:54.472Z",
                        "updatedAt": "2024-12-01T20:57:54.472Z",
                        "id": "674ccdd21058f14d27c5d7a4"
                      }
                    ],
                    "count": 2
                  }
                }
              }
            }
          }
        }
      }
    },
    "/reviews/67c4dc6dd6368f1f29048c4f": {
      "get": {
        "tags": [
          "Reviews"
        ],
        "summary": "Get single review",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "review": {
                      "rating": 1,
                      "title": "Review 2",
                      "comment": "Comment 3",
                      "user": "645f977f0b52892c311eb265",
                      "product": "674c478a397a664d48cd8aec",
                      "createdAt": "2025-03-02T22:32:13.144Z",
                      "updatedAt": "2025-03-02T22:32:13.144Z",
                      "id": "67c4dc6dd6368f1f29048c4f"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/reviews/": {
      "post": {
        "tags": [
          "Reviews"
        ],
        "summary": "Create review",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "product": "674c478a397a664d48cd8aec",
                  "title": "Review 4",
                  "comment": "Comment 4",
                  "rating": 1
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "review": {
                      "rating": 1,
                      "title": "Review 4",
                      "comment": "Comment 4",
                      "user": "645f977f0b52892c311eb265",
                      "product": "674c478a397a664d48cd8aec",
                      "createdAt": "2025-03-02T22:32:13.144Z",
                      "updatedAt": "2025-03-02T22:32:13.144Z",
                      "id": "67c4dc6dd6368f1f29048c4f"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/reviews/643024f86fc6d8750b68a5a8": {
      "patch": {
        "tags": [
          "Reviews"
        ],
        "summary": "Update review",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "product": "64289a8c38b77a3abccf6496",
                  "title": "Review 2",
                  "comment": "Comment 2",
                  "rating": 5
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "review": {
                      "rating": 5,
                      "title": "Review 2",
                      "comment": "Comment 2",
                      "user": "645f977f0b52892c311eb265",
                      "product": "674c478a397a664d48cd8aec",
                      "createdAt": "2025-03-02T22:32:13.144Z",
                      "updatedAt": "2025-03-02T22:39:40.593Z",
                      "id": "67c4dc6dd6368f1f29048c4f"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/reviews/643030362d9e7cec7d713058": {
      "delete": {
        "tags": [
          "Reviews"
        ],
        "summary": "Delete review",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "msg": "Review deleted successfully!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/orders/": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Get all orders",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "orders": [
                      {
                        "tax": 399,
                        "shippingFee": 499,
                        "subTotal": 77997,
                        "total": 78895,
                        "orderItems": [
                          {
                            "name": "accent Chairrr",
                            "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                            "price": 25999,
                            "amount": 3,
                            "product": "674c478a397a664d48cd8aec",
                            "_id": "674d82b878a73a291590a939"
                          }
                        ],
                        "status": "pending",
                        "clientSecret": "RandomValue",
                        "user": "64e0ec0163d91940458da7d1",
                        "createdAt": "2024-12-02T09:49:44.049Z",
                        "updatedAt": "2024-12-02T09:49:44.049Z",
                        "id": "674d82b878a73a291590a938"
                      },
                      {
                        "tax": 399,
                        "shippingFee": 499,
                        "subTotal": 77997,
                        "total": 78895,
                        "orderItems": [
                          {
                            "name": "accent Chairrr",
                            "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                            "price": 25999,
                            "amount": 3,
                            "product": "674c478a397a664d48cd8aec",
                            "_id": "674d832c920fc40fab6a83e3"
                          }
                        ],
                        "status": "pending",
                        "clientSecret": "RandomValue",
                        "user": "64e0ec0163d91940458da7d1",
                        "createdAt": "2024-12-02T09:51:40.505Z",
                        "updatedAt": "2024-12-02T09:51:40.505Z",
                        "id": "674d832c920fc40fab6a83e2"
                      },
                      {
                        "tax": 399,
                        "shippingFee": 499,
                        "subTotal": 77997,
                        "total": 78895,
                        "orderItems": [
                          {
                            "name": "accent Chairrr",
                            "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                            "price": 25999,
                            "amount": 3,
                            "product": "674c478a397a664d48cd8aec",
                            "_id": "674d85fa31c6f82c793714fc"
                          }
                        ],
                        "status": "pending",
                        "clientSecret": "RandomValue",
                        "user": "64e0ec0163d91940458da7d1",
                        "createdAt": "2024-12-02T10:03:38.868Z",
                        "updatedAt": "2024-12-02T10:03:38.868Z",
                        "id": "674d85fa31c6f82c793714fb"
                      }
                    ],
                    "count": 3
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Create order",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "tax": 399,
                  "shippingFee": 499,
                  "items": [
                    {
                      "name": "accent chair",
                      "price": 2599,
                      "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                      "amount": 3,
                      "product": "674c478a397a664d48cd8aec"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "order": {
                      "tax": 399,
                      "shippingFee": 499,
                      "subTotal": 77997,
                      "total": 78895,
                      "orderItems": [
                        {
                          "name": "accent Chairrr",
                          "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                          "price": 25999,
                          "amount": 3,
                          "product": "674c478a397a664d48cd8aec",
                          "_id": "67c4e1aeacf955dc5c5b7835"
                        }
                      ],
                      "status": "pending",
                      "clientSecret": "RandomValue",
                      "user": "645f977f0b52892c311eb265",
                      "createdAt": "2025-03-02T22:54:38.134Z",
                      "updatedAt": "2025-03-02T22:54:38.134Z",
                      "id": "67c4e1aeacf955dc5c5b7834"
                    },
                    "clientSecret": "RandomValue"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/orders/67c4e1aeacf955dc5c5b7834": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Get single order",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "order": {
                      "tax": 399,
                      "shippingFee": 499,
                      "subTotal": 77997,
                      "total": 78895,
                      "orderItems": [
                        {
                          "name": "accent Chairrr",
                          "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                          "price": 25999,
                          "amount": 3,
                          "product": "674c478a397a664d48cd8aec",
                          "_id": "67c4e1aeacf955dc5c5b7835"
                        }
                      ],
                      "status": "pending",
                      "clientSecret": "RandomValue",
                      "user": "645f977f0b52892c311eb265",
                      "createdAt": "2025-03-02T22:54:38.134Z",
                      "updatedAt": "2025-03-02T22:54:38.134Z",
                      "id": "67c4e1aeacf955dc5c5b7834"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Orders"
        ],
        "summary": "Update order",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "paymentID": "RandomID"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "order": {
                      "tax": 399,
                      "shippingFee": 499,
                      "subTotal": 77997,
                      "total": 78895,
                      "orderItems": [
                        {
                          "name": "accent Chairrr",
                          "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                          "price": 25999,
                          "amount": 3,
                          "product": "674c478a397a664d48cd8aec",
                          "_id": "67c4e1aeacf955dc5c5b7835"
                        }
                      ],
                      "status": "paid",
                      "clientSecret": "RandomValue",
                      "user": "645f977f0b52892c311eb265",
                      "createdAt": "2025-03-02T22:54:38.134Z",
                      "updatedAt": "2025-03-02T23:03:14.785Z",
                      "paymentID": "RandomID",
                      "id": "67c4e1aeacf955dc5c5b7834"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/orders/showAllMyOrders": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Get current user orders",
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "orders": [
                      {
                        "tax": 399,
                        "shippingFee": 499,
                        "subTotal": 77997,
                        "total": 78895,
                        "orderItems": [
                          {
                            "name": "accent Chairrr",
                            "image": "https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160",
                            "price": 25999,
                            "amount": 3,
                            "product": "674c478a397a664d48cd8aec",
                            "_id": "67c4e1aeacf955dc5c5b7835"
                          }
                        ],
                        "status": "pending",
                        "clientSecret": "RandomValue",
                        "user": "645f977f0b52892c311eb265",
                        "createdAt": "2025-03-02T22:54:38.134Z",
                        "updatedAt": "2025-03-02T22:54:38.134Z",
                        "id": "67c4e1aeacf955dc5c5b7834"
                      }
                    ],
                    "count": 1
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}